### ISSUE TITLE
align-content stretch's caculation problem

### ISSUE THREAD

**Issue by twxia** [jgthms/css-reference#13]
![screenshot from 2016-11-26 13-04-17](https://cloud.githubusercontent.com/assets/2068895/20638147/e0200972-b3d8-11e6-827c-7169727c5557.png)

http://cssreference.io/#align-content 

Hi ~ Can `align-content: stretch;`'s example add some description about why cause the second line's item are suspending there? 

Reference to the spec: https://drafts.csswg.org/css-flexbox-1/#valdef-align-content-stretch

1. the remain space is: 300px(container) - 100px(line 1 highest item) - 50px(line 2 highest item) = 150px
2. 150px split it up: 150px / 2 = 75px
3. line one's content height: 100px(line 1 highest item) + 75px = 175px
4. line two's content height: 50px(line 2 highest item) + 75px = 125px

The steps may be above steps. 
And the first line red box height is 175px and second line green box is 125px
Like below one: 
![screenshot from 2016-11-28 09-42-10](https://cloud.githubusercontent.com/assets/2068895/20653986/b0310856-b54f-11e6-8a77-8dcbf4ee0d6d.png)

**Comment by jgthms** [comment]
Thanks!
