### ISSUE TITLE
Fix formatting for z-index definition

### ISSUE THREAD

**Issue by valentin-radulescu-hs** [jgthms/css-reference#15]
It reads:

> Defines the order of the elements on the z-axis***8. It only works on positioned** elements (anything apart from static).

It should probably read:

> Defines the order of the elements on the z-axis. **It only works on positioned** elements (anything apart from static).

**Comment by MirShaon** [comment]
:+1:

**Comment by fredericksilva** [comment]
Fixed #1

**Comment by jgthms** [comment]
Thanks!
