### ISSUE TITLE
CanIUse Integration?

### ISSUE THREAD

**Issue by booc0mtaco** [jgthms/css-reference#30]
Some features have varying amounts of support, so I wonder if there's a nice way to reveal whether and where a feature is supported. I initially imagined something sitting adjacent to "link / share / mdn" in some way. Thoughts?

Does Can I Use provide some lightweight API for pulling compatibility information in? or some microformat like:

```( F: 35+ | C: 50+ | S: 10+ | I: Edge )```

**Comment by jgthms** [comment]
Duplicate of #8
