### ISSUE TITLE
Few grammatical errors

### ISSUE THREAD

**Issue by kerreck** [jgthms/css-reference#31]
In _#align-items_ section, _align-items: flex-end;_ property, redundant underscore:

_By default, the cross axis is vertical. This means the flexbox items will be aligned vertically at **the _bottom**._

In _#position_ section, all properties text description refer to yellow block, while block itself is reddish:

_It also makes the element positioned: it will act as an anchor point for the absolutely **positioned yellow block**._

Overall, very useful project for CSS study, thank you.

**Comment by jgthms** [comment]
Thanks!
