### ISSUE TITLE
align-self mistaken description? 

### ISSUE THREAD

**Issue by abumalick** [jgthms/css-reference#35]
Hello, 
I think there is a typo on align-self descriptions
http://cssreference.io/property/align-self/

```
#align-self: flex-start;

If the container has align-items: center and the target has align-items: flex-start, only the target will be at the start of the cross axis.
```
The second rule should be `align-self: flex-start`, shouldn't it?
Same remark for other descriptions of align-self
Thank for your work.

**Comment by jgthms** [comment]
Thanks!
