### ISSUE TITLE
a spelling mistake

### ISSUE THREAD

**Issue by a1exlism** [jgthms/css-reference#36]
Mistake here: http://cssreference.io/#flex-flow
>[https://developer.mozilla.org/en-US/docs/Web/CSS/flex-flow](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-flow)
The flex-flow CSS property is a shorthand property for flex-direction and flex-wrap individual 

So this should be "Shorthand property for flex-direction and `flex-wrap`. "

**Comment by jgthms** [comment]
Thanks!
