### ISSUE TITLE
[Request] Add grid reference

### ISSUE THREAD

**Issue by irfanhudda** [jgthms/css-reference#45]
All major browsers will soon support CSS grids. So it might be a good idea to add CSS grid reference.

PS: 👍 Thanks for this reference. Flexbox visual reference was both comprehensive and concise.

**Comment by jgthms** [comment]
Yeah I need to have a go at CSS grids first. But I'll definitely add it.

**Comment by emyarod** [comment]
I'd love to see a grid reference section being added as well. Please also let me know if there's anything I can do to help out

**Comment by MichaelNeas** [comment]
Bump, thank you for this awesome site! Do you need any assistance with the grid layout?

**Comment by mornir** [comment]
Any update on this? All modern browsers now support CSS Grid and courses like the one from Wes Bos make it more and more popular. I hope that grid references can soon be added.

cssreference.io is already my go-to source of information for Flexbox 🥇

**Comment by mornir** [comment]
https://twitter.com/jgthms/status/957638402224152576

Awesome!!! :100:

**Comment by MichaelNeas** [comment]
https://twitter.com/jgthms/status/958317816897302528 

Looks great :)
