### ISSUE TITLE
Feature request - filter by domain

### ISSUE THREAD

**Issue by jolyonruss** [jgthms/css-reference#9]
First a massive thank you - this is awesome and will I'm sure be a great resource for people learning CSS.

My feature request is to have the ability to filter by domain eg:

Typography:
- font-size
- line-break
- etc

Flexbox:
- display
- flex-basis
- align-items

As someone who's been coding for a while but learning Flexbox being able to see just the Flexbox rules with examples would make it a lot easier. Also, with the typography example, not all the rules are named logically.

**Comment by jgthms** [comment]
Yeah I'm planning on creating "Collections", which would be available at `cssreference.io/flexbox` and just include those properties.

**Comment by jolyonruss** [comment]
I'd love to help out with this, if you want the help and a clear idea of how you would approach it, let me know.

**Comment by jgthms** [comment]
Done! http://cssreference.io/flexbox/
